### PR TITLE
Cropped image

### PR DESCRIPTION
**Pull request by collin**
I had a need for `<CroppedImage/>` in `<bulbs-video>`. So I hoisted it out here.

@kand @daytonn

### CODE REVIEW

**Comment by daytonn** [comment]
👍

**Comment by collin** [comment]
Paging Doctor Kos to the PR @kand

**Comment by kand** [comment]
Would it be possible to have this as a sibling of other components? I can see this component being used externally as well and I think it's a bit confusing to have components in two places in the project.

**Comment by collin** [comment]
That would take some reorganizing of the project layout. Right now everything in `elements/` is built as an individual js file in `dist/`. Shared code that isn't specific to one element currently lives in `lib/`, Store, register, etc.

If we did create a `<cropped-image>` element I think we should be using the react component version inside of other react components rather than always using the `<cropped-image>`.

```
render () {
  return <CroppedImage/>;
}
```

vs

```
render () {
  return <cropped-image/>;
}
```

**Comment by kand** [comment]
👍

**Pull request merged**
