### PR TITLE
bulbs-datamap

### PR DESCRIPTION
**Pull request by spra85**
@collin @daytonn @kand

### CODE REVIEW

**Comment by daytonn** [comment]
seems legit 👍

**Comment by kand** [comment]
👍

**Comment by collin** [comment]
Looks like we need a change to our `.travis.yml`

https://github.com/travis-ci/travis-ci/issues/4771#issuecomment-241439984

**Comment by collin** [comment]
@jmelvnsn Tests pass now. But the linter fails.

**Comment by collin** [comment]
@jmelvnsn linter should be happy now, this can merge whenever

**Pull request merged**
