### PR TITLE
accomodate avclubs comments sharetool

### PR DESCRIPTION
**Pull request by MelizzaP**

### CODE REVIEW

**Comment by MelizzaP** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;NaGsT6NZ&#x2F;14-avc-homepage-player"> AVC homepage player</a>

**Comment by MelizzaP** [comment]
@spra85 @jmelvnsn

**Comment by kand** [comment]
👍

**Comment by spra85** [comment]
👍

**Pull request merged**
