### PR TITLE
clicktracking for notifications

### PR DESCRIPTION
**Pull request by shawncook**
hey @benghaziboy @kand @collin is this a kosher change?

### CODE REVIEW

**Comment by benghaziboy** [comment]
as I understand it, yes. But I am less familiar.
👍

**Comment by collin** [comment]
Yes, those attributes can go on that.

For style we've been splitting multiple attributes like this across new lines:

https://github.com/theonion/bulbs-elements/blob/6dafc0544b1a02a1e64602f8bd23be1d7e3fccb9/elements/bulbs-video/elements/meta/components/campaign.js#L5-L10

**Comment by collin** [comment]
👍

**Comment by kand** [comment]
👍

**Pull request merged**
