### PR TITLE
implement new lint rules

### PR DESCRIPTION
**Pull request by collin**
`no-else-return` and `"space-before-function-paren": [1, "never"],`

@daytonn @kand re: some cleanup from review and getting the function paren style tightened down.

### CODE REVIEW

**Comment by collin** [comment]
This looks big, but it's just linter stuff.

**Comment by kand** [comment]
We should have spaces before function parens, as with all linter rules we're splitting hairs, but it differentiates function calls from function definitions at a glance, given that function calls do not have spaces between the name and the parens (which obviously is standard).

**Comment by collin** [comment]
I concur with your reasoning for switching `space-before-function-paren` from `never` to `always`.

**Comment by kand** [comment]
👍

**Comment by daytonn** [comment]
👍

**Pull request merged**
