### PR TITLE
remove taboola from reading list code

### PR DESCRIPTION
**Pull request by kand**
Updates to reading list code for implementation in onion.

### Release Type: _major_
Removes functionality that sites may be using.

### Removed

1. Reading list no longer manages taboola, this is now a site specific responsibility.

### CODE REVIEW

**Comment by collin** [comment]
👍

**Comment by kand** [comment]
[basic reading list implementation](https://trello.com/c/LYH9p5LW/3-basic-reading-list-implementation)

**Comment by kand** [comment]
[Taboola Audience Exchange Widget](https://trello.com/c/FZoQdrmn/2-taboola-audience-exchange-widget)

**Comment by kand** [comment]
Test failures have nothing to do with this PR, skipping.

**Pull request merged**
