### PR TITLE
Add keys to package.json to make npm stop crying

### PR DESCRIPTION
**Pull request by daytonn**

### CODE REVIEW

**Comment by collin** [comment]
Oh no! That shouldn't be.

We're at `0.2.4` :+1:

**Comment by collin** [comment]
These tests don't run in `.travis.yml` yet, this is good to merge.

**Comment by daytonn** [comment]
I'd like to get this running in travis, tests won't run locally either. Working on that.

**Comment by daytonn** [comment]
So are we good to merge now?

**Comment by collin** [comment]
Yes.

**Pull request merged**
