### PR TITLE
Use different ad block detection, if available

### PR DESCRIPTION
**Pull request by spra85**
Relevant PR with more info in the integrating branch: https://github.com/theonion/omni/pull/1289

### CODE REVIEW

**Comment by brycedorn** [comment]
as an aside, 
```
03 08 2017 17:07:42.828:ERROR [launcher.browserstack]: Can not start safari 9.1 (osx elcapitan)
  Error: Access to API denied. Email to support@browserstack.com for access.
```
doesn't seem to be going away - I just emailed them.

**Comment by spra85** [comment]
@brycedorn, think @mparent61 set up a call with them for this Monday when he's back

**Comment by brycedorn** [comment]
gotcha, won't email.

**Comment by mparent61** [comment]
Yes, I have a phone call with  Browser Stack today.

**Pull request merged**
