### PR TITLE
Fix lint errors on constant condition

### PR DESCRIPTION
**Pull request by daytonn**
@kand @collin This error is preventing me from cutting a release candidate

### CODE REVIEW

**Comment by collin** [comment]
:+1:

**Comment by kand** [comment]
:+1:

For a real implementation, would this be pulled from the env or something?

**Comment by daytonn** [comment]
@kand Yeah we haven't figured out how it will ultimately be implemented. At this point it's very noisy and I think it's more a convenience thing.

**Comment by collin** [comment]
Yeah, originally it was enabled in all dev builds.

It's nice for debugging, but definitely would be nice to figure out how to
keep it out of karma shell output/flag at runtime.

**Pull request merged**
