### PR TITLE
move onion-notifications-off to local instead of session storage

### PR DESCRIPTION
**Pull request by benghaziboy**

### CODE REVIEW

**Comment by collin** [comment]
This seems like a rather blunt instrument. What's the purpose for it?

**Comment by benghaziboy** [comment]
the purpose of the feature or the purpose of the change?

**Comment by collin** [comment]
Of the change. It seems like this change would also alter (greatly restrict) the uses of the notifications feature.

**Comment by benghaziboy** [comment]
sessionStorage doesn't persist across tabs, localStorage does. Needs to change.

**Comment by benghaziboy** [comment]
The idea is if someone closes out of their notification, they should not see another until the browser is closed.

**Comment by collin** [comment]
Right, but `localStorage` won't clear out when the browser is closed. This flag would live forever.

Might have to do something like set a timestamp and do something like:

```
notifications_are_active = 'onion-notifications-off' > n days old
```

**Comment by benghaziboy** [comment]
@collin

**Comment by benghaziboy** [comment]
@kand

**Pull request merged**
