### PR TITLE
react@15.0.0

### PR DESCRIPTION
**Pull request by collin**
@daytonn @kand Checking how we stand up to `react@15.0.0`

### CODE REVIEW

**Comment by collin** [comment]
Moved all the deps to dev dependencies as there was no actual reason for which was were and we don't have an non-dev use for installing deps _**yet**_.

**Comment by kand** [comment]
:+1:

**Comment by collin** [comment]
No more `react-id`, Rejoice!

https://facebook.github.io/react/blog/2016/04/07/react-v15.html

**Comment by collin** [comment]
@daytonn you down with bumping up?

**Comment by daytonn** [comment]
do it 👍 :shipit:

**Pull request merged**
