### PR TITLE
Adding an optional attribute not to add a DFP pixel to the DOM

### PR DESCRIPTION
**Pull request by spra85**
@collin @MelizzaP @kand @daytonn ... Looking for a review on this one.  The purpose of this is to add an optional attribute, `no-pixel` to the campaign-display element that will not add an ad to the DOM unless desired.  The intent is to use this for the slide out navigation on the sites, particularly The Onion.

### CODE REVIEW

**Comment by collin** [comment]
I wonder if it would be wise to wrap `<campaign-display>` in `loadOnDemand` like we do now with `<bulbs-video>`?

**Comment by spra85** [comment]
@collin, I think we'd ultimately probably want to do that as well.  But this covers a different scenario in that we never want to have the ad pixel regardless for the slide out nav

**Comment by collin** [comment]
Gotcha :+1:

**Comment by kand** [comment]
Can you add something about this feature to the [README](https://github.com/theonion/bulbs-elements/blob/22a684efedc6f0cecb9d8d2c85fd6130872450e1/elements/campaign-display/README.md)?

**Pull request merged**
