### PR TITLE
bulbs-content

### PR DESCRIPTION
**Pull request by collin**
@kand

### CODE REVIEW

**Comment by collin** [comment]
@daytonn @spra85 

`<bulbs-liveblog>` adds two two methods for cms-created content to end up on our sites after page load.

This provides an element to wrap our content in. Currently in only emits an event that can be used to initialize inline embeds (twitter, instagram, etc.)

Lo(ooooo)ng-term it would make sense to consolidate all those initializers into this element.

**Comment by kand** [comment]
👍

**Comment by collin** [comment]
@MelizzaP

**Comment by collin** [comment]
@jmelvnsn @shawncook

**Comment by spra85** [comment]
👍

**Pull request merged**
