### PR TITLE
Needed targeting capability to point to specific campaign creative

### PR DESCRIPTION
**Pull request by spra85**

### CODE REVIEW

**Comment by spra85** [comment]
@collin @MelizzaP @daytonn @kand ... This adds a campaign number attribute to bulbs-video to be able to target ads to a specific IO number, which used to be there but with the switch to `bulbs-video` was lost in the old rail player.

**Comment by collin** [comment]
👍

**Comment by kand** [comment]
👍

**Comment by daytonn** [comment]
👍

**Pull request merged**
