### PR TITLE
bulbs-article-body

### PR DESCRIPTION
**Pull request by kand**
New element to apply things to an article body. Need this initially for appending dingbats, but it could be used for other things common to all articles.

### CODE REVIEW

**Comment by kand** [comment]
[cannot click on sponsor link in reading list menu because click event is consumed by item element](https://trello.com/c/UqzwiIW5/39-cannot-click-on-sponsor-link-in-reading-list-menu-because-click-event-is-consumed-by-item-element)

**Comment by kand** [comment]
[use generalized reading list in ON and style](https://trello.com/c/dFCa1o5U/21-use-generalized-reading-list-in-on-and-style)

**Comment by collin** [comment]
@spra85 I agree this hook could get out of hand.

I think the preference is a self-contained element. My guess is nearly all cases would be covered this way (eg. Embedding `<bulbs-video>` in an article body wouldn't need any support from `<bulbs-article-body>`). Something like _dingbat_ or  _inject a dfp slot in between paragraphs_ would be more the sort of thing that fits in this element.

**Comment by spra85** [comment]
@collin, if it's not painful, can you put together a gist for how that might look with the 'inject a dfp slot' example and carry over the conversation to Slack?

**Comment by kand** [comment]
@collin @spra85 are we good on the design?

**Pull request merged**
