### PR TITLE
update rail player targeting

### PR DESCRIPTION
**Pull request by collin**
@spra85 Like this?

### CODE REVIEW

**Comment by spra85** [comment]
@collin, looks right 👍 ... I'm assuming that will work to set the correct prop within the `Revealed` component.

**Comment by collin** [comment]
Yeah, it looks like the correct one to me: https://github.com/theonion/bulbs-elements/blob/master/elements/bulbs-video/components/revealed.js#L72

**Comment by collin** [comment]
@spra85 Will we be able to confirm this easily on a test deploy?

**Comment by spra85** [comment]
Yeah, I can check it for you really quick

**Pull request merged**
