### PR TITLE
pass & test

### PR DESCRIPTION
**Pull request by benghaziboy**
@spra85 @collin

### CODE REVIEW

**Comment by benghaziboy** [comment]
y

**Comment by benghaziboy** [comment]
Yes. This mirrors the behavior of the `targetCampaignId` prop in the `right-rail` so I had to
- Add to the `rail-player` component
- Add to the `rail-player/root` component
- Props are then automatically passed into Revealed and handled as they are other in other contexts.

**Comment by spra85** [comment]
LGTM @benghaziboy.  Guessing then we'll need an additional change in the `omni` repo that passes the new attr in?

**Comment by benghaziboy** [comment]
Yes. Doing a temp release to make that change atm.

**Comment by benghaziboy** [comment]
[Pass `targetSpecialCoverage` through the elements `rail-player.js` component & the `rail-player/root.js` component to `revealed.js](https://trello.com/c/oNaQWmel/1257-pass-targetspecialcoverage-through-the-elements-rail-player-js-component-the-rail-player-root-js-component-to-revealed-js)

**Pull request merged**
