### PR TITLE
allow a more specific clickable area in reading list menus

### PR DESCRIPTION
**Pull request by kand**
Allows a more limited clickable area in a reading list menu item, addresses the issue where we want the feature type and campaign to be clickable for their own URLs apart from scrolling to a reading list article.

### CODE REVIEW

**Comment by collin** [comment]
Could we achieve this by having the menu item ignore clicks that are on an `<a>` tag? Or is there something that prevents that?

**Comment by kand** [comment]
An explicit area that is clickable makes for more sensible markup. With this change it will be obvious what areas in the markup correspond to scrolling an item as opposed to click logic that ignores some parts of the markup and is hidden in the the javascript.

**Comment by collin** [comment]
👍

**Comment by kand** [comment]
[cannot click on sponsor link in reading list menu because click event is consumed by item element](https://trello.com/c/UqzwiIW5/39-cannot-click-on-sponsor-link-in-reading-list-menu-because-click-event-is-consumed-by-item-element)

**Pull request merged**
