### PR TITLE
[WIP] Video carousel campaign

### PR DESCRIPTION
**Pull request by collin**
changes according to: https://trello.com/c/p1g1YlP1/62-sponsored-content-treatment-on-the-player

### CODE REVIEW

**Comment by collin** [comment]
@spra85 @jmelvnsn 

Changes per the trello board:

(once approved this will merge into `video-carouser-refactor`)

**Comment by spra85** [comment]
LGTM

**Comment by collin** [comment]
@kand @daytonn

**Comment by collin** [comment]
Travis failures are in the coveralls runner. It's running out of memory and politely crashing.

**Comment by kand** [comment]
👍

**Pull request merged**
